version: '2'

services:
  web:
    build: .
    volumes:
      - .:/apps/study
      - bundle_cache:/bundle_cache
    command: sh -c 'bundle install'
    dns:
      - 192.168.39.1
      - 8.8.8.8

volumes:
  bundle_cache:
